spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/votacao_pauta
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

user:
  info:
    url: ${USER_INFO_URL:http://localhost:8081}